### ISSUE TITLE
Template functions rather than strings ...

### ISSUE THREAD

**Issue by jamesladd** [petermichaux/maria#74]
If I would rather have a function called to provide my views template string can I simply supply my own getTemplate function in my view? 

I'm assuming the mechanism that looks up a variable with the same name as my View will first see if I have a getTemplate function?

**Comment by petermichaux** [comment]
I cannot be sure this is a common use case and it seems it is solvable by plugin. The ability to solve problems like this with plugins is what Maria is all about.
