### ISSUE TITLE
Child views selecting where they are appended ...

### ISSUE THREAD

**Issue by jamesladd** [petermichaux/maria#81]
We would like to be able to tell a parent view where to append a child view with more control.  

Currently you have this:

```
1 maria.ElementView.prototype.buildChildViews = function() {
2    var childViews = this.childNodes;
3    for (var i = 0, ilen = childViews.length; i < ilen; i++) {
4        this.getContainerEl().appendChild(childViews[i].build());
5    }
6 };
```

Would it be possible to change line 4 to ask the child view where it should be appended and if not specified by the child only then chooses the this.getContainerEl() ?

For example: 

4        this.getContainerEl().appendChild(childViews[i].build(),  toolbarElement());

This would help us in situations like this:

```
<div class='a'>
  <div class="column1">
  </div>
  <div class="column2">
  </div>
  <div class="toolbar">
  </div>
</div>
```

And we want the child view to be in one of 'column1' or 'column2' or 'toolbar' 
rather than all being siblings inside of 'a' (current functionality)

**Comment by petermichaux** [comment]
Please reopen if you'd like to continue the conversation.
