### ISSUE TITLE
Broken TodoMVC link 

### ISSUE THREAD

**Issue by marcin-wosinek** [petermichaux/maria#84]
The 'TodoMVC' link at [project home](http://peter.michaux.ca/maria/) page leads to
http://todomvc.com/architecture-examples/maria/
while currently url should be
http://todomvc.com/examples/maria/

is the home page generated from source so I can provide PR?

**Comment by petermichaux** [comment]
Thanks. It is unfortunate that the people at the TodoMVC project did not add some 301 redirects.

This problem is actually already fixed. I just haven't released the newest version of the Maria website.

https://github.com/petermichaux/maria/commit/052e6af0e3e1ae6c7c9b786b5abcf1d4d5ecf0b5

**Comment by marcin-wosinek** [comment]
How are realising the new website versions? Probably this can be automated with travis-ci

**Comment by petermichaux** [comment]
fix published
